# Generated by Django 6.0.2 on 2026-02-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
